#!/bin/bash
#
# A simple script to simplify uploading using the command line.
#

curl="/usr/bin/curl"

function upload {
    file=$1
    tag=$2

    if [ ! -f "${file}" ]; then
        echo "${file} is not a file. Aborting."
        exit 2
    fi

    if [ -x /usr/bin/md5sum ]; then
        md5=$(md5sum "$file" | awk '{print $1}')
    fi
    
    if [ -x /sbin/md5 ]; then
        md5=$(md5 "$file" | awk '{print $NF}')
    fi

    if [ -z $md5 ]; then
        echo "ERROR: Unable to calculate MD5 checksum of $file"
        exit 2
    fi

    size=$(stat -c%s "$file")

    filename=$(basename "${file}")
    echo "File path: ${file}"
    echo "File name: ${filename}"
    echo "Bytes:     ${size}"
    echo "Checksum:  ${md5}"

    start=$(date +%s%N)
    ${curl} -s -S -L -H "x-filename: ${filename}" -H "x-size: ${size}" -H "x-md5: $md5" -H "x-tag: $tag" --data-binary "@${file}" "http://filebin.net/uploader" > /dev/null
    if [ $? -eq 0 ]; then
        echo "Status:    Success"
    else
        echo "Status:    Failed"
    fi
    end=$(date +%s%N)
    elapsed=$(echo "scale=8; ($end - $start) / 1000000000" | bc)
    echo "Elapsed:   $elapsed sec"
    echo " "
}

if [ ! -e "$curl" ]; then
    echo "ERROR: Unable to execute $curl"
    exit 2
fi

path="$1"
tag="$2"

if [ -z "$path" ]; then
    echo "ERROR: Path not set."
    exit 2
fi

if [ -z "$tag" ]; then
    echo "ERROR: Tag not set."
    exit 2
fi

if [ -d "$path" ]; then
    echo "Specified path ($path) is a directory. Traversing..."
    find "$path" -type f | while read f; do
        upload "$f" "$tag"
    done
elif [ -f "$path" ]; then
    upload "$path" "$tag"
else
    echo "$path is unknown."
fi

#
#echo $curl
